spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/images
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG